// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/datetime/datetime.proto

/*
Package datetime is a generated protocol buffer package.

It is generated from these files:
	protos/datetime/datetime.proto

It has these top-level messages:
	Date
	DateRange
	DateRanges
*/
package datetime

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Date struct {
	Day   int32 `protobuf:"varint,1,opt,name=day" json:"day,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Year  int32 `protobuf:"varint,3,opt,name=year" json:"year,omitempty"`
}

func (m *Date) Reset()                    { *m = Date{} }
func (m *Date) String() string            { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()               {}
func (*Date) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type DateRange struct {
	Start *Date `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   *Date `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
}

func (m *DateRange) Reset()                    { *m = DateRange{} }
func (m *DateRange) String() string            { return proto.CompactTextString(m) }
func (*DateRange) ProtoMessage()               {}
func (*DateRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DateRange) GetStart() *Date {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *DateRange) GetEnd() *Date {
	if m != nil {
		return m.End
	}
	return nil
}

type DateRanges struct {
	Ranges []*DateRange `protobuf:"bytes,1,rep,name=ranges" json:"ranges,omitempty"`
}

func (m *DateRanges) Reset()                    { *m = DateRanges{} }
func (m *DateRanges) String() string            { return proto.CompactTextString(m) }
func (*DateRanges) ProtoMessage()               {}
func (*DateRanges) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DateRanges) GetRanges() []*DateRange {
	if m != nil {
		return m.Ranges
	}
	return nil
}

func init() {
	proto.RegisterType((*Date)(nil), "datetime.Date")
	proto.RegisterType((*DateRange)(nil), "datetime.DateRange")
	proto.RegisterType((*DateRanges)(nil), "datetime.DateRanges")
}

func init() { proto.RegisterFile("protos/datetime/datetime.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x0a, 0x82, 0x40,
	0x10, 0x86, 0xb1, 0x55, 0xa9, 0x11, 0x22, 0xa6, 0x0e, 0x7b, 0x0a, 0x91, 0x0e, 0x42, 0x60, 0x60,
	0xa7, 0xae, 0xd1, 0x13, 0xd8, 0x13, 0x4c, 0x38, 0x54, 0x07, 0x35, 0xd6, 0xb9, 0xf8, 0xf6, 0xb1,
	0x63, 0x79, 0xa8, 0xdb, 0x3f, 0xf3, 0xfd, 0xfb, 0x2d, 0x03, 0xdb, 0x97, 0xeb, 0xa4, 0xeb, 0x0f,
	0x35, 0x09, 0xcb, 0xb3, 0xe1, 0x29, 0x14, 0x0a, 0x70, 0xfe, 0x9d, 0xb3, 0x33, 0x84, 0x17, 0x12,
	0xc6, 0x15, 0x98, 0x9a, 0x06, 0x1b, 0xa4, 0x41, 0x1e, 0x55, 0x3e, 0xe2, 0x06, 0xa2, 0xa6, 0x6b,
	0xe5, 0x61, 0x67, 0xba, 0x1b, 0x07, 0x44, 0x08, 0x07, 0x26, 0x67, 0x8d, 0x2e, 0x35, 0x67, 0x57,
	0x58, 0x78, 0x47, 0x45, 0xed, 0x9d, 0x71, 0x07, 0x51, 0x2f, 0xe4, 0x44, 0x55, 0x49, 0xb9, 0x2c,
	0xa6, 0xaf, 0xb5, 0x33, 0x42, 0x4c, 0xc1, 0x70, 0x5b, 0xab, 0xfa, 0xbf, 0xe3, 0x51, 0x76, 0x02,
	0x98, 0xa4, 0x3d, 0xee, 0x21, 0x76, 0x9a, 0x6c, 0x90, 0x9a, 0x3c, 0x29, 0xd7, 0x3f, 0x4f, 0x3c,
	0xab, 0x3e, 0x95, 0x5b, 0xac, 0x47, 0x1e, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78, 0xce, 0x3b,
	0x9a, 0x06, 0x01, 0x00, 0x00,
}
